from tkinter import *
from tkinter import ttk
 
root = Tk()
root.title("Автосервис «АвтоТранс»")
root.geometry("1920x1080")
root.attributes("-toolwindow", True)
root.minsize(320,240)
root.maxsize(1920,1080) 
icon = PhotoImage(file = "i.png")
root.iconphoto(True, icon)

label = ttk.Label(text="Добро пожаловать, что вы хотите сделать?")
label.pack()

def noprofile():
    windownp = Tk()
    windownp.title("Главная страница")
    windownp.geometry("1920x1080")
    windownp.attributes("-toolwindow", True)
    label = ttk.Label(windownp, text="Скоро тут чото будет (за эту упшку я узнал больше чем за 3 года в этом «прекрасном» колледже)")
    windownp.minsize(320,240)
    windownp.maxsize(1920,1080)
    close_button = ttk.Button(windownp, text = "Вернуться на главную", command = lambda: windownp.destroy())
    close_button.pack()
    close_button.place(relx=0.75, rely=0.45, width=200, height=70)
    label.pack()

def client():
    windowc = Tk()
    windowc.title("Главная страница")
    windowc.geometry("1920x1080")
    windowc.attributes("-toolwindow", True)
    label = ttk.Label(windowc, text="Введите данные профиля:")
    windowc.minsize(320,240)
    windowc.maxsize(1920,1080)
    close_button = ttk.Button(windowc, text = "Вернуться на главную", command = lambda: windowc.destroy())
    close_button.pack()
    close_button.place(relx=0.75, rely=0.45, width=200, height=70)
    text = ttk.Entry(windowc)
    text.pack()
    text.place(relx=0.45, rely=0.45, width=200, height=70)
    label.pack()
def admin():
    windowa = Tk()
    windowa.title("Главная страница")
    windowa.geometry("1920x1080")
    windowa.attributes("-toolwindow", True)
    label = ttk.Label(windowa, text="Войдите со своим аккаунтом администратора:")
    windowa.minsize(320,240)
    windowa.maxsize(1920,1080)
    close_button = ttk.Button(windowa, text = "Вернуться на главную", command = lambda: windowa.destroy())
    close_button.pack()
    close_button.place(relx=0.75, rely=0.45, width=200, height=70)
    text = ttk.Entry(windowa)
    text.pack()
    text.place(relx=0.45, rely=0.45, width=200, height=70)
    label.pack()

btn = ttk.Button(text = "Войти в свой профиль", command = client)
btn.pack()
btn.place(relx=0.15, rely=0.45, width=200, height=70)
btn = ttk.Button(text = "Я сотрудник", command = admin)
btn.pack()
btn.place(relx=0.45, rely=0.45, width=200, height=70)
btn = ttk.Button(text = "Продолжить без профиля", command = noprofile)
btn.pack()
btn.place(relx=0.75, rely=0.45, width=200, height=70)

root.mainloop()